package textdecorators;

public enum PrefixSuffix {

	BEGIN_SENTENCE__,
	__END_SENTENCE,
	SPELLCHECK_,
	_SPELLCHECK,
	MOST_FREQUENT_,
	_MOST_FREQUENT,
	KEYWORD_,
	_KEYWORD,
	SENETENCEDECORATOR__,
	__SENETENCEDECORATOR,
	SPELLCHECKDECORATOR__,
	__SPELLCHECKDECORATOR,
	KEYWORDDECORATOR__,
	__KEYWORDDECORATOR,
	MOSTFREQUENTWORDDECORATOR__,
	__MOSTFREQUENTWORDDECORATOR,
	NONE;
	
}
